name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 602a7fe5-c562-4dfd-b315-1aab55930d12
          heroku_app_name: samzc1
          heroku_email: b148579e-7a00-4699-8988-8dcb98f8740e
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_CONFIG_FILE_URL: https://gist.githubusercontent.com/Snax-phycho/8b6d95e8b2825cbbbbaa574b52a9df7b/raw/config.env
