name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: b148579e-7a00-4699-8988-8dcb98f8740e
          heroku_app_name: samzc4
          heroku_email: djkgcbafsxbcuvv@candassociates.com
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_CONFIG_FILE_URL: https://gist.githubusercontent.com/Snax-phycho/c1af4783a3db051531666645ede87b0e/raw/Config.env
